// ═══════════════════════════════════════════════════════
// FinMatrix — Pre-seeded Inventory Items (30 own + 15 agency)
// ═══════════════════════════════════════════════════════

export interface InventoryItemData {
  itemId: string;
  companyId: string;
  sku: string;
  name: string;
  description: string;
  category: string;
  unitOfMeasure: string;
  costMethod: 'FIFO' | 'LIFO' | 'Weighted Average';
  unitCost: number;
  sellingPrice: number;
  quantityOnHand: number;
  quantityOnOrder: number;
  quantityCommitted: number;
  reorderPoint: number;
  reorderQuantity: number;
  minStock: number;
  maxStock: number;
  isActive: boolean;
  serialTracking: boolean;
  lotTracking: boolean;
  barcodeData: string;
  locationId: string;
  sourceAgencyId?: string;
  imageUrl: string;
  lastUpdated: string;
}

export type InventoryCategory =
  | 'Electronics'
  | 'Office Supplies'
  | 'Furniture'
  | 'Cleaning Supplies'
  | 'Packaging';

export const INVENTORY_CATEGORIES: InventoryCategory[] = [
  'Electronics',
  'Office Supplies',
  'Furniture',
  'Cleaning Supplies',
  'Packaging',
];

// ── Stock movement history (for detail screen) ──────
export interface StockMovement {
  id: string;
  itemId: string;
  type: 'Purchase' | 'Sale' | 'Adjustment' | 'Transfer' | 'Return';
  quantity: number;
  reference: string;
  note: string;
  performedBy: string;
  date: string;
}

// ═══════════════════════════════════════════════════════
// 30 Company-owned Inventory Items (5 categories × 6)
// ═══════════════════════════════════════════════════════
export const inventoryItemsData: InventoryItemData[] = [
  // ── Electronics (6) ───────────────────────────────
  {
    itemId: 'inv-001',
    companyId: 'comp-001',
    sku: 'ELC-LAP-001',
    name: 'Business Laptop 15"',
    description: 'Intel i7, 16GB RAM, 512GB SSD business laptop',
    category: 'Electronics',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 85000,
    sellingPrice: 105000,
    quantityOnHand: 25,
    quantityOnOrder: 10,
    quantityCommitted: 5,
    reorderPoint: 10,
    reorderQuantity: 20,
    minStock: 5,
    maxStock: 50,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567001',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-10T14:30:00Z',
  },
  {
    itemId: 'inv-002',
    companyId: 'comp-001',
    sku: 'ELC-MON-001',
    name: '27" LED Monitor',
    description: '4K UHD LED monitor, HDMI + DisplayPort',
    category: 'Electronics',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 32000,
    sellingPrice: 42000,
    quantityOnHand: 40,
    quantityOnOrder: 0,
    quantityCommitted: 8,
    reorderPoint: 15,
    reorderQuantity: 25,
    minStock: 10,
    maxStock: 80,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567002',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-08T09:15:00Z',
  },
  {
    itemId: 'inv-003',
    companyId: 'comp-001',
    sku: 'ELC-KBD-001',
    name: 'Wireless Keyboard',
    description: 'Bluetooth mechanical keyboard, slim profile',
    category: 'Electronics',
    unitOfMeasure: 'Unit',
    costMethod: 'Weighted Average',
    unitCost: 3500,
    sellingPrice: 5200,
    quantityOnHand: 150,
    quantityOnOrder: 50,
    quantityCommitted: 20,
    reorderPoint: 40,
    reorderQuantity: 100,
    minStock: 20,
    maxStock: 300,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567003',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-12T11:00:00Z',
  },
  {
    itemId: 'inv-004',
    companyId: 'comp-001',
    sku: 'ELC-MOU-001',
    name: 'Ergonomic Mouse',
    description: 'Wireless ergonomic mouse with adjustable DPI',
    category: 'Electronics',
    unitOfMeasure: 'Unit',
    costMethod: 'Weighted Average',
    unitCost: 1800,
    sellingPrice: 2800,
    quantityOnHand: 3,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 30,
    reorderQuantity: 80,
    minStock: 15,
    maxStock: 200,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567004',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-01T08:45:00Z',
  },
  {
    itemId: 'inv-005',
    companyId: 'comp-001',
    sku: 'ELC-UPS-001',
    name: 'UPS 1000VA',
    description: 'Uninterruptible power supply, 1000VA/600W',
    category: 'Electronics',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 12000,
    sellingPrice: 16500,
    quantityOnHand: 0,
    quantityOnOrder: 15,
    quantityCommitted: 0,
    reorderPoint: 5,
    reorderQuantity: 15,
    minStock: 3,
    maxStock: 30,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567005',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-02-28T16:20:00Z',
  },
  {
    itemId: 'inv-006',
    companyId: 'comp-001',
    sku: 'ELC-CAB-HDMI',
    name: 'HDMI Cable 2m',
    description: 'High-speed HDMI 2.1 cable, 2 metres',
    category: 'Electronics',
    unitOfMeasure: 'Piece',
    costMethod: 'Weighted Average',
    unitCost: 350,
    sellingPrice: 600,
    quantityOnHand: 200,
    quantityOnOrder: 0,
    quantityCommitted: 30,
    reorderPoint: 50,
    reorderQuantity: 150,
    minStock: 25,
    maxStock: 500,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567006',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-11T10:00:00Z',
  },

  // ── Office Supplies (6) ───────────────────────────
  {
    itemId: 'inv-007',
    companyId: 'comp-001',
    sku: 'OFS-PPR-A4',
    name: 'A4 Copy Paper (Ream)',
    description: '500-sheet ream, 80gsm white A4 paper',
    category: 'Office Supplies',
    unitOfMeasure: 'Ream',
    costMethod: 'Weighted Average',
    unitCost: 650,
    sellingPrice: 850,
    quantityOnHand: 300,
    quantityOnOrder: 100,
    quantityCommitted: 50,
    reorderPoint: 80,
    reorderQuantity: 200,
    minStock: 40,
    maxStock: 600,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567007',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-09T13:00:00Z',
  },
  {
    itemId: 'inv-008',
    companyId: 'comp-001',
    sku: 'OFS-PEN-BLK',
    name: 'Ballpoint Pen (Black) Box',
    description: 'Box of 50 black ballpoint pens',
    category: 'Office Supplies',
    unitOfMeasure: 'Box',
    costMethod: 'FIFO',
    unitCost: 400,
    sellingPrice: 600,
    quantityOnHand: 80,
    quantityOnOrder: 0,
    quantityCommitted: 10,
    reorderPoint: 20,
    reorderQuantity: 50,
    minStock: 10,
    maxStock: 150,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567008',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-05T10:30:00Z',
  },
  {
    itemId: 'inv-009',
    companyId: 'comp-001',
    sku: 'OFS-TNR-001',
    name: 'Laser Printer Toner',
    description: 'Compatible toner cartridge for HP LaserJet',
    category: 'Office Supplies',
    unitOfMeasure: 'Cartridge',
    costMethod: 'FIFO',
    unitCost: 2800,
    sellingPrice: 4000,
    quantityOnHand: 8,
    quantityOnOrder: 12,
    quantityCommitted: 3,
    reorderPoint: 10,
    reorderQuantity: 20,
    minStock: 5,
    maxStock: 40,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567009',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-07T15:45:00Z',
  },
  {
    itemId: 'inv-010',
    companyId: 'comp-001',
    sku: 'OFS-STP-001',
    name: 'Heavy-Duty Stapler',
    description: 'Metal stapler, 100-sheet capacity',
    category: 'Office Supplies',
    unitOfMeasure: 'Unit',
    costMethod: 'Weighted Average',
    unitCost: 900,
    sellingPrice: 1400,
    quantityOnHand: 45,
    quantityOnOrder: 0,
    quantityCommitted: 5,
    reorderPoint: 10,
    reorderQuantity: 30,
    minStock: 5,
    maxStock: 80,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567010',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-03T12:00:00Z',
  },
  {
    itemId: 'inv-011',
    companyId: 'comp-001',
    sku: 'OFS-FLD-001',
    name: 'Manila File Folders (25-pack)',
    description: 'Legal-size manila file folders, pack of 25',
    category: 'Office Supplies',
    unitOfMeasure: 'Pack',
    costMethod: 'FIFO',
    unitCost: 350,
    sellingPrice: 520,
    quantityOnHand: 0,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 15,
    reorderQuantity: 40,
    minStock: 8,
    maxStock: 100,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567011',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-02-20T09:00:00Z',
  },
  {
    itemId: 'inv-012',
    companyId: 'comp-001',
    sku: 'OFS-WBD-001',
    name: 'Whiteboard Markers (12-pack)',
    description: 'Assorted color dry-erase markers, 12 pack',
    category: 'Office Supplies',
    unitOfMeasure: 'Pack',
    costMethod: 'Weighted Average',
    unitCost: 550,
    sellingPrice: 800,
    quantityOnHand: 60,
    quantityOnOrder: 20,
    quantityCommitted: 0,
    reorderPoint: 15,
    reorderQuantity: 40,
    minStock: 8,
    maxStock: 120,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567012',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-06T14:20:00Z',
  },

  // ── Furniture (6) ─────────────────────────────────
  {
    itemId: 'inv-013',
    companyId: 'comp-001',
    sku: 'FRN-DSK-001',
    name: 'Executive Office Desk',
    description: 'L-shaped executive desk, walnut finish',
    category: 'Furniture',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 28000,
    sellingPrice: 38000,
    quantityOnHand: 6,
    quantityOnOrder: 4,
    quantityCommitted: 2,
    reorderPoint: 3,
    reorderQuantity: 6,
    minStock: 2,
    maxStock: 15,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567013',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-10T16:00:00Z',
  },
  {
    itemId: 'inv-014',
    companyId: 'comp-001',
    sku: 'FRN-CHR-001',
    name: 'Ergonomic Office Chair',
    description: 'Mesh-back ergonomic chair with lumbar support',
    category: 'Furniture',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 18000,
    sellingPrice: 25000,
    quantityOnHand: 12,
    quantityOnOrder: 8,
    quantityCommitted: 3,
    reorderPoint: 5,
    reorderQuantity: 10,
    minStock: 3,
    maxStock: 25,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567014',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-09T11:30:00Z',
  },
  {
    itemId: 'inv-015',
    companyId: 'comp-001',
    sku: 'FRN-CAB-001',
    name: 'Filing Cabinet 4-Drawer',
    description: 'Steel 4-drawer filing cabinet with lock',
    category: 'Furniture',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 9500,
    sellingPrice: 13500,
    quantityOnHand: 2,
    quantityOnOrder: 0,
    quantityCommitted: 1,
    reorderPoint: 3,
    reorderQuantity: 5,
    minStock: 2,
    maxStock: 12,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567015',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-04T08:15:00Z',
  },
  {
    itemId: 'inv-016',
    companyId: 'comp-001',
    sku: 'FRN-SHF-001',
    name: 'Bookshelf 5-Tier',
    description: 'Wooden 5-tier bookshelf, oak finish',
    category: 'Furniture',
    unitOfMeasure: 'Unit',
    costMethod: 'Weighted Average',
    unitCost: 7500,
    sellingPrice: 11000,
    quantityOnHand: 0,
    quantityOnOrder: 6,
    quantityCommitted: 0,
    reorderPoint: 2,
    reorderQuantity: 5,
    minStock: 1,
    maxStock: 10,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567016',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-02-25T10:00:00Z',
  },
  {
    itemId: 'inv-017',
    companyId: 'comp-001',
    sku: 'FRN-TBL-001',
    name: 'Conference Table 8-Seater',
    description: 'Oval conference table, seats 8, with cable port',
    category: 'Furniture',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 45000,
    sellingPrice: 62000,
    quantityOnHand: 3,
    quantityOnOrder: 0,
    quantityCommitted: 1,
    reorderPoint: 1,
    reorderQuantity: 3,
    minStock: 1,
    maxStock: 6,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567017',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-11T09:45:00Z',
  },
  {
    itemId: 'inv-018',
    companyId: 'comp-001',
    sku: 'FRN-PRT-001',
    name: 'Desk Partition Screen',
    description: 'Acoustic desk partition, 120cm wide',
    category: 'Furniture',
    unitOfMeasure: 'Unit',
    costMethod: 'Weighted Average',
    unitCost: 4200,
    sellingPrice: 6000,
    quantityOnHand: 18,
    quantityOnOrder: 0,
    quantityCommitted: 4,
    reorderPoint: 5,
    reorderQuantity: 10,
    minStock: 3,
    maxStock: 30,
    isActive: false,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567018',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-02-14T15:30:00Z',
  },

  // ── Cleaning Supplies (6) ─────────────────────────
  {
    itemId: 'inv-019',
    companyId: 'comp-001',
    sku: 'CLN-SAN-001',
    name: 'Hand Sanitizer 500ml',
    description: '70% alcohol hand sanitizer gel, pump bottle',
    category: 'Cleaning Supplies',
    unitOfMeasure: 'Bottle',
    costMethod: 'FIFO',
    unitCost: 280,
    sellingPrice: 420,
    quantityOnHand: 120,
    quantityOnOrder: 0,
    quantityCommitted: 15,
    reorderPoint: 30,
    reorderQuantity: 80,
    minStock: 15,
    maxStock: 250,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567019',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-12T08:00:00Z',
  },
  {
    itemId: 'inv-020',
    companyId: 'comp-001',
    sku: 'CLN-DSF-001',
    name: 'Surface Disinfectant Spray',
    description: 'Multi-surface disinfectant spray, 750ml',
    category: 'Cleaning Supplies',
    unitOfMeasure: 'Bottle',
    costMethod: 'Weighted Average',
    unitCost: 320,
    sellingPrice: 480,
    quantityOnHand: 75,
    quantityOnOrder: 40,
    quantityCommitted: 10,
    reorderPoint: 25,
    reorderQuantity: 60,
    minStock: 12,
    maxStock: 200,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567020',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-10T10:30:00Z',
  },
  {
    itemId: 'inv-021',
    companyId: 'comp-001',
    sku: 'CLN-MOP-001',
    name: 'Spin Mop Set',
    description: 'Self-wringing spin mop with bucket',
    category: 'Cleaning Supplies',
    unitOfMeasure: 'Set',
    costMethod: 'FIFO',
    unitCost: 1500,
    sellingPrice: 2200,
    quantityOnHand: 10,
    quantityOnOrder: 5,
    quantityCommitted: 2,
    reorderPoint: 5,
    reorderQuantity: 10,
    minStock: 3,
    maxStock: 25,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567021',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-08T14:00:00Z',
  },
  {
    itemId: 'inv-022',
    companyId: 'comp-001',
    sku: 'CLN-TIS-001',
    name: 'Tissue Paper Roll (12-pack)',
    description: 'Soft 2-ply tissue paper, 12 rolls per pack',
    category: 'Cleaning Supplies',
    unitOfMeasure: 'Pack',
    costMethod: 'Weighted Average',
    unitCost: 450,
    sellingPrice: 650,
    quantityOnHand: 180,
    quantityOnOrder: 0,
    quantityCommitted: 25,
    reorderPoint: 40,
    reorderQuantity: 100,
    minStock: 20,
    maxStock: 350,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567022',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-07T12:15:00Z',
  },
  {
    itemId: 'inv-023',
    companyId: 'comp-001',
    sku: 'CLN-GLV-001',
    name: 'Disposable Gloves (Box of 100)',
    description: 'Nitrile powder-free gloves, medium size',
    category: 'Cleaning Supplies',
    unitOfMeasure: 'Box',
    costMethod: 'FIFO',
    unitCost: 700,
    sellingPrice: 1000,
    quantityOnHand: 4,
    quantityOnOrder: 20,
    quantityCommitted: 2,
    reorderPoint: 10,
    reorderQuantity: 25,
    minStock: 5,
    maxStock: 60,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567023',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-02T09:30:00Z',
  },
  {
    itemId: 'inv-024',
    companyId: 'comp-001',
    sku: 'CLN-TRB-001',
    name: 'Trash Bags 50L (Roll of 30)',
    description: 'Black heavy-duty trash bags, 50 litre, 30 per roll',
    category: 'Cleaning Supplies',
    unitOfMeasure: 'Roll',
    costMethod: 'Weighted Average',
    unitCost: 250,
    sellingPrice: 380,
    quantityOnHand: 90,
    quantityOnOrder: 0,
    quantityCommitted: 12,
    reorderPoint: 20,
    reorderQuantity: 50,
    minStock: 10,
    maxStock: 150,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567024',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-06T11:00:00Z',
  },

  // ── Packaging (6) ─────────────────────────────────
  {
    itemId: 'inv-025',
    companyId: 'comp-001',
    sku: 'PKG-BOX-SM',
    name: 'Shipping Box Small',
    description: 'Corrugated cardboard box 30×20×15cm',
    category: 'Packaging',
    unitOfMeasure: 'Piece',
    costMethod: 'Weighted Average',
    unitCost: 45,
    sellingPrice: 75,
    quantityOnHand: 500,
    quantityOnOrder: 200,
    quantityCommitted: 80,
    reorderPoint: 100,
    reorderQuantity: 300,
    minStock: 50,
    maxStock: 1000,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567025',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-12T07:00:00Z',
  },
  {
    itemId: 'inv-026',
    companyId: 'comp-001',
    sku: 'PKG-BOX-LG',
    name: 'Shipping Box Large',
    description: 'Corrugated cardboard box 60×40×30cm',
    category: 'Packaging',
    unitOfMeasure: 'Piece',
    costMethod: 'Weighted Average',
    unitCost: 85,
    sellingPrice: 130,
    quantityOnHand: 250,
    quantityOnOrder: 0,
    quantityCommitted: 40,
    reorderPoint: 60,
    reorderQuantity: 200,
    minStock: 30,
    maxStock: 600,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567026',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-11T13:30:00Z',
  },
  {
    itemId: 'inv-027',
    companyId: 'comp-001',
    sku: 'PKG-BUB-001',
    name: 'Bubble Wrap Roll 50m',
    description: 'Air cushion bubble wrap, 50m × 1m roll',
    category: 'Packaging',
    unitOfMeasure: 'Roll',
    costMethod: 'FIFO',
    unitCost: 800,
    sellingPrice: 1200,
    quantityOnHand: 15,
    quantityOnOrder: 10,
    quantityCommitted: 3,
    reorderPoint: 5,
    reorderQuantity: 15,
    minStock: 3,
    maxStock: 30,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567027',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-09T16:00:00Z',
  },
  {
    itemId: 'inv-028',
    companyId: 'comp-001',
    sku: 'PKG-TAP-001',
    name: 'Packing Tape (6-pack)',
    description: 'Clear packing tape 48mm × 100m, 6 rolls',
    category: 'Packaging',
    unitOfMeasure: 'Pack',
    costMethod: 'Weighted Average',
    unitCost: 380,
    sellingPrice: 550,
    quantityOnHand: 70,
    quantityOnOrder: 30,
    quantityCommitted: 8,
    reorderPoint: 15,
    reorderQuantity: 40,
    minStock: 8,
    maxStock: 120,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567028',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-03-05T14:45:00Z',
  },
  {
    itemId: 'inv-029',
    companyId: 'comp-001',
    sku: 'PKG-STR-001',
    name: 'Stretch Film 500mm',
    description: 'Pallet stretch wrap, 500mm × 300m',
    category: 'Packaging',
    unitOfMeasure: 'Roll',
    costMethod: 'FIFO',
    unitCost: 600,
    sellingPrice: 900,
    quantityOnHand: 0,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 4,
    reorderQuantity: 10,
    minStock: 2,
    maxStock: 20,
    isActive: false,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567029',
    locationId: 'loc-warehouse',
    imageUrl: '',
    lastUpdated: '2026-01-15T08:00:00Z',
  },
  {
    itemId: 'inv-030',
    companyId: 'comp-001',
    sku: 'PKG-LBL-001',
    name: 'Shipping Labels (500-sheet)',
    description: 'Self-adhesive A6 shipping labels, 500 sheets',
    category: 'Packaging',
    unitOfMeasure: 'Pack',
    costMethod: 'Weighted Average',
    unitCost: 1200,
    sellingPrice: 1800,
    quantityOnHand: 20,
    quantityOnOrder: 0,
    quantityCommitted: 2,
    reorderPoint: 5,
    reorderQuantity: 15,
    minStock: 3,
    maxStock: 40,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567030',
    locationId: 'loc-main',
    imageUrl: '',
    lastUpdated: '2026-03-04T10:20:00Z',
  },
];

// ═══════════════════════════════════════════════════════
// 15 Agency-sourced Items (5 per agency × 3 agencies)
// ═══════════════════════════════════════════════════════
export const agencyInventoryItemsData: InventoryItemData[] = [
  // ── Dalda Cooking Oil (agency_dalda) ──────────────
  {
    itemId: 'inv-ag-001',
    companyId: 'comp-001',
    sku: 'DLD-OIL-1L',
    name: 'Dalda Cooking Oil 1L',
    description: 'Premium fortified cooking oil, 1 litre bottle',
    category: 'Cooking Oil',
    unitOfMeasure: 'Bottle',
    costMethod: 'FIFO',
    unitCost: 380,
    sellingPrice: 450,
    quantityOnHand: 500,
    quantityOnOrder: 200,
    quantityCommitted: 60,
    reorderPoint: 100,
    reorderQuantity: 300,
    minStock: 50,
    maxStock: 800,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234568001',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_dalda',
    imageUrl: '',
    lastUpdated: '2026-03-12T06:00:00Z',
  },
  {
    itemId: 'inv-ag-002',
    companyId: 'comp-001',
    sku: 'DLD-OIL-5L',
    name: 'Dalda Cooking Oil 5L',
    description: 'Premium fortified cooking oil, 5 litre can',
    category: 'Cooking Oil',
    unitOfMeasure: 'Can',
    costMethod: 'FIFO',
    unitCost: 1750,
    sellingPrice: 2100,
    quantityOnHand: 200,
    quantityOnOrder: 100,
    quantityCommitted: 30,
    reorderPoint: 50,
    reorderQuantity: 150,
    minStock: 25,
    maxStock: 400,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234568002',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_dalda',
    imageUrl: '',
    lastUpdated: '2026-03-11T07:30:00Z',
  },
  {
    itemId: 'inv-ag-003',
    companyId: 'comp-001',
    sku: 'DLD-BAN-1KG',
    name: 'Dalda Banaspati Ghee 1kg',
    description: 'Vegetable ghee, 1kg pack',
    category: 'Cooking Oil',
    unitOfMeasure: 'Pack',
    costMethod: 'FIFO',
    unitCost: 420,
    sellingPrice: 520,
    quantityOnHand: 350,
    quantityOnOrder: 0,
    quantityCommitted: 40,
    reorderPoint: 80,
    reorderQuantity: 200,
    minStock: 40,
    maxStock: 500,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234568003',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_dalda',
    imageUrl: '',
    lastUpdated: '2026-03-10T12:00:00Z',
  },
  {
    itemId: 'inv-ag-004',
    companyId: 'comp-001',
    sku: 'DLD-BAN-5KG',
    name: 'Dalda Banaspati Ghee 5kg',
    description: 'Vegetable ghee, 5kg tin',
    category: 'Cooking Oil',
    unitOfMeasure: 'Tin',
    costMethod: 'FIFO',
    unitCost: 1950,
    sellingPrice: 2400,
    quantityOnHand: 8,
    quantityOnOrder: 50,
    quantityCommitted: 5,
    reorderPoint: 40,
    reorderQuantity: 100,
    minStock: 20,
    maxStock: 250,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234568004',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_dalda',
    imageUrl: '',
    lastUpdated: '2026-03-09T08:45:00Z',
  },
  {
    itemId: 'inv-ag-005',
    companyId: 'comp-001',
    sku: 'DLD-OLV-500M',
    name: 'Dalda Olive Oil 500ml',
    description: 'Extra virgin olive oil, 500ml bottle',
    category: 'Cooking Oil',
    unitOfMeasure: 'Bottle',
    costMethod: 'FIFO',
    unitCost: 850,
    sellingPrice: 1100,
    quantityOnHand: 0,
    quantityOnOrder: 60,
    quantityCommitted: 0,
    reorderPoint: 30,
    reorderQuantity: 80,
    minStock: 15,
    maxStock: 150,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234568005',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_dalda',
    imageUrl: '',
    lastUpdated: '2026-03-08T15:00:00Z',
  },

  // ── AquaPure Water Supply (agency_aquapure) ───────
  {
    itemId: 'inv-ag-006',
    companyId: 'comp-001',
    sku: 'AQP-500ML',
    name: 'AquaPure Water 500ml',
    description: 'Mineral water bottle, 500ml',
    category: 'Bottled Water',
    unitOfMeasure: 'Bottle',
    costMethod: 'Weighted Average',
    unitCost: 25,
    sellingPrice: 40,
    quantityOnHand: 2000,
    quantityOnOrder: 500,
    quantityCommitted: 200,
    reorderPoint: 500,
    reorderQuantity: 1000,
    minStock: 250,
    maxStock: 5000,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568006',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_aquapure',
    imageUrl: '',
    lastUpdated: '2026-03-13T06:00:00Z',
  },
  {
    itemId: 'inv-ag-007',
    companyId: 'comp-001',
    sku: 'AQP-1500ML',
    name: 'AquaPure Water 1.5L',
    description: 'Mineral water bottle, 1.5 litres',
    category: 'Bottled Water',
    unitOfMeasure: 'Bottle',
    costMethod: 'Weighted Average',
    unitCost: 45,
    sellingPrice: 70,
    quantityOnHand: 1200,
    quantityOnOrder: 300,
    quantityCommitted: 100,
    reorderPoint: 300,
    reorderQuantity: 600,
    minStock: 150,
    maxStock: 3000,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568007',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_aquapure',
    imageUrl: '',
    lastUpdated: '2026-03-13T06:15:00Z',
  },
  {
    itemId: 'inv-ag-008',
    companyId: 'comp-001',
    sku: 'AQP-19L',
    name: 'AquaPure Dispenser Bottle 19L',
    description: 'Large dispenser refill bottle, 19 litres',
    category: 'Bottled Water',
    unitOfMeasure: 'Bottle',
    costMethod: 'Weighted Average',
    unitCost: 100,
    sellingPrice: 160,
    quantityOnHand: 5,
    quantityOnOrder: 50,
    quantityCommitted: 3,
    reorderPoint: 100,
    reorderQuantity: 200,
    minStock: 50,
    maxStock: 500,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568008',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_aquapure',
    imageUrl: '',
    lastUpdated: '2026-03-12T14:30:00Z',
  },
  {
    itemId: 'inv-ag-009',
    companyId: 'comp-001',
    sku: 'AQP-DISP-HOT',
    name: 'AquaPure Hot & Cold Dispenser',
    description: 'Floor-standing hot & cold water dispenser unit',
    category: 'Bottled Water',
    unitOfMeasure: 'Unit',
    costMethod: 'FIFO',
    unitCost: 8500,
    sellingPrice: 12000,
    quantityOnHand: 50,
    quantityOnOrder: 10,
    quantityCommitted: 5,
    reorderPoint: 10,
    reorderQuantity: 20,
    minStock: 5,
    maxStock: 80,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234568009',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_aquapure',
    imageUrl: '',
    lastUpdated: '2026-03-07T11:00:00Z',
  },
  {
    itemId: 'inv-ag-010',
    companyId: 'comp-001',
    sku: 'AQP-CASE-24',
    name: 'AquaPure Water Case (24×500ml)',
    description: 'Case of 24 bottles, 500ml each',
    category: 'Bottled Water',
    unitOfMeasure: 'Case',
    costMethod: 'Weighted Average',
    unitCost: 550,
    sellingPrice: 800,
    quantityOnHand: 300,
    quantityOnOrder: 0,
    quantityCommitted: 40,
    reorderPoint: 75,
    reorderQuantity: 150,
    minStock: 35,
    maxStock: 500,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568010',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_aquapure',
    imageUrl: '',
    lastUpdated: '2026-03-10T09:00:00Z',
  },

  // ── SparkClean Detergents (agency_sparkclean) ─────
  {
    itemId: 'inv-ag-011',
    companyId: 'comp-001',
    sku: 'SC-DET-1KG',
    name: 'SparkClean Detergent Powder 1kg',
    description: 'Washing powder with active enzymes, 1kg pack',
    category: 'Detergent',
    unitOfMeasure: 'Pack',
    costMethod: 'Weighted Average',
    unitCost: 180,
    sellingPrice: 250,
    quantityOnHand: 800,
    quantityOnOrder: 200,
    quantityCommitted: 100,
    reorderPoint: 200,
    reorderQuantity: 400,
    minStock: 100,
    maxStock: 1200,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568011',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_sparkclean',
    imageUrl: '',
    lastUpdated: '2026-03-12T10:00:00Z',
  },
  {
    itemId: 'inv-ag-012',
    companyId: 'comp-001',
    sku: 'SC-DET-5KG',
    name: 'SparkClean Detergent Powder 5kg',
    description: 'Bulk washing powder, 5kg bag',
    category: 'Detergent',
    unitOfMeasure: 'Bag',
    costMethod: 'Weighted Average',
    unitCost: 800,
    sellingPrice: 1100,
    quantityOnHand: 3,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 80,
    reorderQuantity: 150,
    minStock: 40,
    maxStock: 400,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568012',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_sparkclean',
    imageUrl: '',
    lastUpdated: '2026-03-06T08:30:00Z',
  },
  {
    itemId: 'inv-ag-013',
    companyId: 'comp-001',
    sku: 'SC-LIQ-1L',
    name: 'SparkClean Liquid Detergent 1L',
    description: 'Concentrated liquid wash, 1 litre bottle',
    category: 'Detergent',
    unitOfMeasure: 'Bottle',
    costMethod: 'Weighted Average',
    unitCost: 280,
    sellingPrice: 380,
    quantityOnHand: 600,
    quantityOnOrder: 100,
    quantityCommitted: 50,
    reorderPoint: 150,
    reorderQuantity: 300,
    minStock: 75,
    maxStock: 900,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568013',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_sparkclean',
    imageUrl: '',
    lastUpdated: '2026-03-11T14:00:00Z',
  },
  {
    itemId: 'inv-ag-014',
    companyId: 'comp-001',
    sku: 'SC-DISH-500M',
    name: 'SparkClean Dishwash Liquid 500ml',
    description: 'Lemon-fresh dishwashing liquid, 500ml',
    category: 'Detergent',
    unitOfMeasure: 'Bottle',
    costMethod: 'Weighted Average',
    unitCost: 120,
    sellingPrice: 175,
    quantityOnHand: 0,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 250,
    reorderQuantity: 500,
    minStock: 120,
    maxStock: 1200,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568014',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_sparkclean',
    imageUrl: '',
    lastUpdated: '2026-02-28T10:00:00Z',
  },
  {
    itemId: 'inv-ag-015',
    companyId: 'comp-001',
    sku: 'SC-FLOOR-1L',
    name: 'SparkClean Floor Cleaner 1L',
    description: 'Pine-scented floor cleaner, 1 litre',
    category: 'Detergent',
    unitOfMeasure: 'Bottle',
    costMethod: 'Weighted Average',
    unitCost: 150,
    sellingPrice: 220,
    quantityOnHand: 450,
    quantityOnOrder: 0,
    quantityCommitted: 35,
    reorderPoint: 120,
    reorderQuantity: 250,
    minStock: 60,
    maxStock: 700,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234568015',
    locationId: 'loc-warehouse',
    sourceAgencyId: 'agency_sparkclean',
    imageUrl: '',
    lastUpdated: '2026-03-09T13:15:00Z',
  },
];

// ═══════════════════════════════════════════════════════
// Combined + stock movement helpers
// ═══════════════════════════════════════════════════════
export const allInventoryItems: InventoryItemData[] = [
  ...inventoryItemsData,
  ...agencyInventoryItemsData,
];

export const stockMovementsData: StockMovement[] = [
  { id: 'mv-001', itemId: 'inv-001', type: 'Purchase', quantity: 30, reference: 'PO-2026-001', note: 'Initial stock purchase', performedBy: 'Admin', date: '2026-01-15T10:00:00Z' },
  { id: 'mv-002', itemId: 'inv-001', type: 'Sale', quantity: -5, reference: 'SO-2026-012', note: 'Sold to client', performedBy: 'Admin', date: '2026-02-20T14:30:00Z' },
  { id: 'mv-003', itemId: 'inv-004', type: 'Sale', quantity: -47, reference: 'SO-2026-033', note: 'Bulk order dispatch', performedBy: 'Admin', date: '2026-02-28T09:00:00Z' },
  { id: 'mv-004', itemId: 'inv-004', type: 'Return', quantity: 3, reference: 'RET-2026-004', note: 'Customer return (defective)', performedBy: 'Admin', date: '2026-03-01T08:45:00Z' },
  { id: 'mv-005', itemId: 'inv-005', type: 'Purchase', quantity: 15, reference: 'PO-2026-011', note: 'Restock on order', performedBy: 'Admin', date: '2026-03-05T12:00:00Z' },
  { id: 'mv-006', itemId: 'inv-007', type: 'Adjustment', quantity: -20, reference: 'ADJ-2026-001', note: 'Damaged in transit', performedBy: 'Admin', date: '2026-02-15T16:00:00Z' },
  { id: 'mv-007', itemId: 'inv-011', type: 'Sale', quantity: -15, reference: 'SO-2026-041', note: 'Office supplies order', performedBy: 'Admin', date: '2026-02-10T10:30:00Z' },
  { id: 'mv-008', itemId: 'inv-013', type: 'Purchase', quantity: 8, reference: 'PO-2026-015', note: 'New furniture batch', performedBy: 'Admin', date: '2026-03-01T08:00:00Z' },
  { id: 'mv-009', itemId: 'inv-013', type: 'Sale', quantity: -2, reference: 'SO-2026-050', note: 'Sold to corporate client', performedBy: 'Admin', date: '2026-03-07T14:00:00Z' },
  { id: 'mv-010', itemId: 'inv-016', type: 'Transfer', quantity: -3, reference: 'TRF-2026-002', note: 'Transferred to branch', performedBy: 'Admin', date: '2026-02-20T11:00:00Z' },
  { id: 'mv-011', itemId: 'inv-025', type: 'Purchase', quantity: 300, reference: 'PO-2026-020', note: 'Packaging restock', performedBy: 'Admin', date: '2026-03-10T07:00:00Z' },
  { id: 'mv-012', itemId: 'inv-ag-001', type: 'Purchase', quantity: 500, reference: 'PO-AG-2026-001', note: 'Agency replenishment', performedBy: 'Admin', date: '2026-03-08T06:00:00Z' },
  { id: 'mv-013', itemId: 'inv-ag-001', type: 'Sale', quantity: -120, reference: 'SO-2026-060', note: 'Retail distribution', performedBy: 'Admin', date: '2026-03-11T10:30:00Z' },
  { id: 'mv-014', itemId: 'inv-ag-006', type: 'Purchase', quantity: 2000, reference: 'PO-AG-2026-005', note: 'Bulk water purchase', performedBy: 'Admin', date: '2026-03-12T06:00:00Z' },
  { id: 'mv-015', itemId: 'inv-ag-011', type: 'Sale', quantity: -150, reference: 'SO-2026-072', note: 'Wholesale distribution', performedBy: 'Admin', date: '2026-03-12T09:45:00Z' },
  { id: 'mv-016', itemId: 'inv-ag-014', type: 'Adjustment', quantity: -50, reference: 'ADJ-2026-003', note: 'Expired stock write-off', performedBy: 'Admin', date: '2026-02-28T10:00:00Z' },
  { id: 'mv-017', itemId: 'inv-019', type: 'Purchase', quantity: 100, reference: 'PO-2026-025', note: 'Cleaning supplies restock', performedBy: 'Admin', date: '2026-03-10T08:00:00Z' },
  { id: 'mv-018', itemId: 'inv-023', type: 'Sale', quantity: -8, reference: 'SO-2026-078', note: 'Office cleaning order', performedBy: 'Admin', date: '2026-03-01T11:00:00Z' },
];

export const getStockMovements = (itemId: string): StockMovement[] =>
  stockMovementsData.filter(m => m.itemId === itemId);
