export const ROUTES = {
  ONBOARDING: 'Onboarding',
  ROLE_SELECTION: 'RoleSelection',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  FORGOT_PASSWORD: 'ForgotPassword',
  EMAIL_VERIFICATION: 'EmailVerification',
  COMPANY_SETUP: 'CompanySetup',
  CREATE_COMPANY: 'CreateCompany',
  JOIN_COMPANY: 'JoinCompany',
  DELIVERY_ONBOARDING: 'DeliveryOnboarding',
  ADMIN_TABS: 'AdminTabs',
  ADMIN_DASHBOARD: 'AdminDashboard',
  TRANSACTIONS_HUB: 'TransactionsHub',
  REPORTS_HUB: 'ReportsHub',
  INVENTORY_HUB: 'InventoryHub',
  MORE_HUB: 'MoreHub',
  DELIVERY_TABS: 'DeliveryTabs',
  DP_DASHBOARD: 'DPDashboard',
  DP_DELIVERIES: 'DPDeliveries',
  DP_INVENTORY: 'DPInventory',
  DP_PROFILE: 'DPProfile',
} as const;
