// ═══════════════════════════════════════════════════════
// FinMatrix — Reconciliation Slice (createAppSlice pattern)
// ═══════════════════════════════════════════════════════

import { createSelector, type PayloadAction } from '@reduxjs/toolkit';
import { createAppSlice } from '@store/createAppSlice';
import type { BankTransaction } from '../../../types';
import {
  createBankReconciliationAPI,
  getUnreconciledTransactionsAPI,
  createBankTransactionAPI,
} from '../../../network/bankingNetwork';
import {
  bankReconciliationSingleSerializer,
  bankTransactionListSerializer,
  bankTransactionSingleSerializer,
} from '../../../serializers/bankingSerializer';

export type ReconciliationStep = 1 | 2 | 3;

export interface ReconciliationState {
  step: ReconciliationStep;
  selectedAccountId: string;
  statementDate: string;
  beginningBalance: string;
  endingBalance: string;
  unclearedTransactions: BankTransaction[];
  selectedTransactionIds: string[];
  adjustmentTransactionId: string;
  isLoading: boolean;
  isSaving: boolean;
  isAdjusting: boolean;
  error: string;
}

const initialState: ReconciliationState = {
  step: 1,
  selectedAccountId: '',
  statementDate: new Date().toISOString().slice(0, 10),
  beginningBalance: '0',
  endingBalance: '0',
  unclearedTransactions: [],
  selectedTransactionIds: [],
  adjustmentTransactionId: '',
  isLoading: false,
  isSaving: false,
  isAdjusting: false,
  error: '',
};

const signedAmount = (tx: BankTransaction): number => {
  if (tx.type === 'deposit' || tx.type === 'interest' || tx.type === 'card_payment') return tx.amount;
  if (tx.type === 'withdrawal' || tx.type === 'fee' || tx.type === 'card_charge') return -tx.amount;
  if (tx.type === 'transfer') {
    const fromDirection = /transfer to/i.test(tx.description);
    return fromDirection ? -tx.amount : tx.amount;
  }
  return 0;
};

export const reconciliationSlice = createAppSlice({
  name: 'reconciliation',
  initialState,
  reducers: create => ({
    resetReconciliationState: create.reducer(() => initialState),
    setReconciliationStep: create.reducer((state, action: PayloadAction<ReconciliationStep>) => {
      state.step = action.payload;
    }),
    setReconciliationAccountId: create.reducer((state, action: PayloadAction<string>) => {
      state.selectedAccountId = action.payload;
      state.selectedTransactionIds = [];
      state.adjustmentTransactionId = '';
    }),
    setStatementDate: create.reducer((state, action: PayloadAction<string>) => {
      state.statementDate = action.payload;
    }),
    setBeginningBalance: create.reducer((state, action: PayloadAction<string>) => {
      state.beginningBalance = action.payload;
    }),
    setEndingBalance: create.reducer((state, action: PayloadAction<string>) => {
      state.endingBalance = action.payload;
    }),
    toggleTransactionCleared: create.reducer((state, action: PayloadAction<string>) => {
      const id = action.payload;
      if (state.selectedTransactionIds.includes(id)) {
        state.selectedTransactionIds = state.selectedTransactionIds.filter(x => x !== id);
      } else {
        state.selectedTransactionIds.push(id);
      }
    }),

    fetchUnclearedTransactions: create.asyncThunk(
      async (payload: { bankAccountId: string; statementDate: string }) => {
        const envelope = await getUnreconciledTransactionsAPI(
          payload.bankAccountId,
          payload.statementDate,
        );
        return bankTransactionListSerializer(envelope);
      },
      {
        pending: state => {
          state.isLoading = true;
          state.error = '';
        },
        fulfilled: (state, action) => {
          state.unclearedTransactions = action.payload;
          const validIds = new Set(action.payload.map(tx => tx.id));
          state.selectedTransactionIds = state.selectedTransactionIds.filter(id => validIds.has(id));
          state.isLoading = false;
        },
        rejected: (state, action) => {
          state.isLoading = false;
          state.error = action.error?.message ?? 'Failed to fetch uncleared transactions';
        },
      },
    ),

    addReconciliationAdjustment: create.asyncThunk(
      async (
        payload: {
          bankAccountId: string;
          date: string;
          difference: number;
          statementDate: string;
        },
      ) => {
        const adjustmentType = payload.difference > 0 ? 'interest' : 'fee';
        const createdEnvelope = await createBankTransactionAPI({
          bankAccountId: payload.bankAccountId,
          date: payload.date,
          payee: 'Reconciliation Adjustment',
          description: 'Auto adjustment from reconciliation',
          type: adjustmentType,
          amount: Math.abs(payload.difference),
          memo: 'Generated by reconciliation',
          isReconciled: false,
        });
        const created = bankTransactionSingleSerializer(createdEnvelope);

        const refreshedEnvelope = await getUnreconciledTransactionsAPI(
          payload.bankAccountId,
          payload.statementDate,
        );
        const rows = bankTransactionListSerializer(refreshedEnvelope);
        return { createdId: created?.id ?? '', rows };
      },
      {
        pending: state => {
          state.isAdjusting = true;
          state.error = '';
        },
        fulfilled: (state, action) => {
          state.isAdjusting = false;
          state.adjustmentTransactionId = action.payload.createdId;
          state.unclearedTransactions = action.payload.rows;
          if (!state.selectedTransactionIds.includes(action.payload.createdId)) {
            state.selectedTransactionIds.push(action.payload.createdId);
          }
        },
        rejected: (state, action) => {
          state.isAdjusting = false;
          state.error = action.error?.message ?? 'Failed to add adjustment';
        },
      },
    ),

    finalizeReconciliation: create.asyncThunk(
      async (payload: {
        bankAccountId: string;
        statementDate: string;
        beginningBalance: number;
        endingBalance: number;
        clearedTransactionIds: string[];
        adjustmentTransactionId?: string | null;
      }) => {
        const envelope = await createBankReconciliationAPI({
          ...payload,
          adjustmentTransactionId: payload.adjustmentTransactionId ?? null,
        });
        return bankReconciliationSingleSerializer(envelope);
      },
      {
        pending: state => {
          state.isSaving = true;
          state.error = '';
        },
        fulfilled: state => {
          state.isSaving = false;
        },
        rejected: (state, action) => {
          state.isSaving = false;
          state.error = action.error?.message ?? 'Failed to finalize reconciliation';
        },
      },
    ),
  }),

  selectors: {
    selectReconciliationState: state => state,
    selectReconciliationStep: state => state.step,
    selectReconciliationAccountId: state => state.selectedAccountId,
    selectReconciliationStatementDate: state => state.statementDate,
    selectReconciliationBeginningBalance: state => state.beginningBalance,
    selectReconciliationEndingBalance: state => state.endingBalance,
    selectReconciliationUnclearedTransactions: state => state.unclearedTransactions,
    selectReconciliationSelectedTransactionIds: state => state.selectedTransactionIds,
    selectReconciliationIsLoading: state => state.isLoading,
    selectReconciliationIsSaving: state => state.isSaving,
    selectReconciliationIsAdjusting: state => state.isAdjusting,
    selectReconciliationError: state => state.error,
    selectReconciliationPayments: createSelector(
      [(state: ReconciliationState) => state.unclearedTransactions],
      transactions => transactions.filter(tx => signedAmount(tx) < 0),
    ),
    selectReconciliationDeposits: createSelector(
      [(state: ReconciliationState) => state.unclearedTransactions],
      transactions => transactions.filter(tx => signedAmount(tx) >= 0),
    ),
    selectReconciliationClearedBalance: state => {
      const begin = parseFloat(state.beginningBalance) || 0;
      const selected = new Set(state.selectedTransactionIds);
      const delta = state.unclearedTransactions
        .filter(tx => selected.has(tx.id))
        .reduce((sum, tx) => sum + signedAmount(tx), 0);
      return begin + delta;
    },
    selectReconciliationDifference: state => {
      const begin = parseFloat(state.beginningBalance) || 0;
      const ending = parseFloat(state.endingBalance) || 0;
      const selected = new Set(state.selectedTransactionIds);
      const delta = state.unclearedTransactions
        .filter(tx => selected.has(tx.id))
        .reduce((sum, tx) => sum + signedAmount(tx), 0);
      const cleared = begin + delta;
      return ending - cleared;
    },
    selectReconciliationIsBalanced: state => {
      const begin = parseFloat(state.beginningBalance) || 0;
      const ending = parseFloat(state.endingBalance) || 0;
      const selected = new Set(state.selectedTransactionIds);
      const delta = state.unclearedTransactions
        .filter(tx => selected.has(tx.id))
        .reduce((sum, tx) => sum + signedAmount(tx), 0);
      const diff = ending - (begin + delta);
      return Math.abs(diff) < 0.01;
    },
  },
});

export const {
  resetReconciliationState,
  setReconciliationStep,
  setReconciliationAccountId,
  setStatementDate,
  setBeginningBalance,
  setEndingBalance,
  toggleTransactionCleared,
  fetchUnclearedTransactions,
  addReconciliationAdjustment,
  finalizeReconciliation,
} = reconciliationSlice.actions;

export const {
  selectReconciliationState,
  selectReconciliationStep,
  selectReconciliationAccountId,
  selectReconciliationStatementDate,
  selectReconciliationBeginningBalance,
  selectReconciliationEndingBalance,
  selectReconciliationUnclearedTransactions,
  selectReconciliationSelectedTransactionIds,
  selectReconciliationIsLoading,
  selectReconciliationIsSaving,
  selectReconciliationIsAdjusting,
  selectReconciliationError,
  selectReconciliationPayments,
  selectReconciliationDeposits,
  selectReconciliationClearedBalance,
  selectReconciliationDifference,
  selectReconciliationIsBalanced,
} = reconciliationSlice.selectors;
